baseurl       = "https://github.com/bjango/Hugs"
languagecode  = "en-us"
title         = "Hugs"
uglyurls      = false
disableKinds  = ["section", "RSS", "sitemap", "robotsTXT", "taxonomyTerm"]

[params]
    Title = "Title here"
    SiteDescription = "Description here."
    author = ""
