baseurl       = "https://github.com/bjango/Hugs"
languagecode  = "en-us"
title         = "Hugs"
uglyurls      = false
disableKinds  = ["RSS", "sitemap", "robotsTXT"]

[taxonomies]
  category = "categories"

[params]
    Title = "Title here"
    SiteDescription = "Description here."
    author = ""
